if has('win32')
  set guifont=DejaVu_Sans_Mono:h12:cANSI:qDRAFT
else
  set guifont=Monospace\ 11
endif

filetype detect " from https://stackoverflow.com/a/65367744
exec 'set columns=' . get({'tex': 95, 'ps1': 120}, &filetype, 85)
set lines=24

" Disable beeping. It seems not all systems need this
" setting but some do so it's included here for safety.
set visualbell t_vb=

" Make focus follow mouse:
set mousefocus
"set scrollfocus

" Disable toolbar since it is so big in GTK3:
set guioptions-=T
