#!/bin/sh

# Example for $XDG_CONFIG_HOME/nsxiv/exec/image-info
# Called by nsxiv(1) whenever an image gets loaded.
# The output is displayed in nsxiv's status bar.
# Arguments:
#   $1: path to image file
#   $2: image width
#   $3: image height

exec 2>/dev/null

#filename=$(basename -- "$1")
filename="${1##*/}"
#filesize=$(du -Hh -- "$1" | cut -f 1)
geometry="${2}x${3}"

#a="$(wmctrl -l | awk '/nsxiv/ {print $1}')"
#sleep 1 && wmctrl -N "${filename} (${geometry})" -ir "$a" &
#notify-send -- "$a"

#printf %s "${filename} (${geometry})"
printf %s "${filename} (${geometry}) $(date -r "$1" +%Y-%m-%d)"
